name: nexus
description: "NEXUS — personal hub for study, life, and money."
publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.2
  image_picker: ^1.2.3
  shared_preferences: ^2.5.5
  crypto: ^3.0.7
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  cloud_firestore: ^6.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/branding/nexus_mark.png
